---

- name: Prepare Statsd directory
  file: state=directory path={{statsd_home}}

- name: Install statsd
  npm: name=statsd path={{statsd_home}}

- name: Install extra NPM dependencies
  npm: name={{item}} path={{statsd_home}}
  with_items: "{{statsd_extra_dependencies}}"

- name: Create node user
  user: name={{statsd_user}} state=present shell=/bin/false system=yes

- name: Configure systemd
  template: src=systemd.service.j2 dest=/etc/systemd/system/{{statsd_title}}.service
  notify:
  - "{{statsd_title}} restart"

- name: Configure statsd
  template: src=statsd.js.j2 dest={{statsd_home}}/config.js
  notify:
  - "{{statsd_title}} restart"

- name: Ensure that Statsd is started
  service: name={{statsd_title}} state=started enabled=yes
